const defaultTheme = require('tailwindcss/defaultTheme')
const defaultColors = require ('./config/colors')

module.exports = {
  target: [
    'ie11',
    {
      objectFit: 'relaxed',
      objectPosition: 'relaxed',
      position: 'relaxed',
    },
  ],
  theme: {
    borderRadius: {
      none: '0',
      sm: '0.125rem',
      default: '0.125rem',
      md: '0.375rem',
      full: '9999px',
    },
    borderWidth: {
      0: '0px',
      default: '1px',
      2: '2px',
      3: '3px',
      4: '4px',
    },
    boxShadow: {
      outline: defaultTheme.boxShadow.outline,
      default: '0 0 4px rgba(0, 0, 0, 0.2)',
      none: '0 0 0 rgba(0, 0, 0, 0)',
      sm: '0 0 1px rgba(0, 0, 0, 0.5)',
      lg: '0 0 6px rgba(0, 0, 0, 0.2)',
      xl: '0 3px 20px rgba(0, 0, 0, 0.1)',
      inset: 'inset 0 0 1px rgba(0, 0, 0, 0.5)',
      'inset-lg': 'inset 0 0 1px rgba(0, 0, 0, 0.5), 0 0 6px rgba(0, 0, 0, 0.2)',
      'inset-xl': 'inset 0 0 1px rgba(0, 0, 0, 0.5), 0 3px 20px rgba(0, 0, 0, 0.1)',
    },
    colors: {
      ...defaultColors,
    },
    fontFamily: {
      sans: ['Lato', ...defaultTheme.fontFamily.sans],
      serif: ['Noe', ...defaultTheme.fontFamily.serif],
      mono: ['Consolas', ...defaultTheme.fontFamily.mono],
      tech: ['Barlow', 'Lato', ...defaultTheme.fontFamily.sans],
    },
    fontWeight: {
      light: '300',
      normal: '400',
      medium: '500',
      bold: '700',
      black: '900',
    },
    minHeight: {
      '0': '0',
      '10vh': '10vh',
      '20vh': '20vh',
      '30vh': '30vh',
      '40vh': '40vh',
      '50vh': '50vh',
      '60vh': '60vh',
      '70vh': '70vh',
      '80vh': '80vh',
      '90vh': '90vh',
      '100vh': '100vh',
      screen: '100vh',
      full: '100%',
    },
    maxHeight: {
      '0': '0',
      ...defaultTheme.maxHeight,
    },
    opacity: {
      '0': 0,
      '025': 0.025,
      '05': 0.05,
      '10': 0.1,
      '20': 0.2,
      '30': 0.3,
      '40': 0.4,
      '50': 0.5,
      '60': 0.6,
      '70': 0.7,
      '80': 0.8,
      '90': 0.9,
      '100': 1,
    },
    rotate: {
      45: '45deg',
      90: '90deg',
      135: '135deg',
      180: '180deg',
      225: '225deg',
      270: '270deg',
      315: '315deg',
    },
    spacing: {
      ...defaultTheme.spacing,
      '2px': '2px',
      '80': '20rem',
      '96': '24rem',
      '128': '32rem',
    },
    textSize: {
      xs: '0.76rem',
      sm: '0.88rem',
      base: '1rem',
      lg: '1.24rem',
      xl: '1.375rem',
      '2xl': '1.80rem',
      '3xl': '2.66rem',
      '4xl': '3.00rem',
      '5xl': '3.75rem',
      '6xl': '4.50rem',
    },
    zIndex: {
      auto: 'auto',
      behind: -1,
      '0': '0',
      '10': '10',
      '20': '20',
      '30': '30',
      '40': '40',
      '50': '50',
      max: 1000,
    },
    aspectRatios: ['21x9', '16x9', '4x3', '3x2', '8x5', '5x8', '1x1'],
    gradients: theme => ({
      directions: ['90deg', '135deg'],
      colors: {
        'red-orange': [theme('colors.red.700'), theme('colors.orange.500')],
        'orange-tan': [theme('colors.orange.500'), theme('colors.tan.400')],
        'tan-red': [theme('colors.tan.400'), theme('colors.red.700')],
        'red-yellow': [theme('colors.red.700'), theme('colors.yellow.500')],
        'yellow-orange': [theme('colors.yellow.500'), theme('colors.orange.500')],
        'green-yellow': [theme('colors.green.500'), theme('colors.yellow.500')],
        'blue-teal': [theme('colors.blue.700'), theme('colors.teal.400')],
        'aqua-blue-dark': [theme('colors.aqua.500'), theme('colors.blue.900')],
        'blue-dark-teal': [theme('colors.blue.900'), theme('colors.teal.400')],
        'teal-green': [theme('colors.teal.400'), theme('colors.green.500')],
        'blue-green': [theme('colors.blue.700'), theme('colors.green.500')],
        'blue-gray-cool': [theme('colors.blue.700'), theme('colors.gray-cool.500')],
        'blue-dark-gray-warm': [theme('colors.blue.900'), theme('colors.gray-warm.700')],
        'blue-gray-warm': [theme('colors.blue.700'), theme('colors.gray-warm.700')],
        'gray-cool-blue-dark': [theme('colors.gray-cool.500'), theme('colors.blue.900')],
        'gold-tan': [theme('colors.gold.500'), theme('colors.tan.400')],
        'red-blue': [theme('colors.red.700'), theme('colors.blue.700')],
        'blue-orange': [theme('colors.blue.700'), theme('colors.orange.500')],
        'aqua-yellow': [theme('colors.aqua.500'), theme('colors.yellow.500')],
        'yellow-blue': [theme('colors.yellow.500'), theme('colors.blue.700')],
      },
    }),
    transformOrigin: {
      center: 'center',
      top: 'top',
      'top-right': 'top right',
      right: 'right',
      'bottom-right': 'bottom right',
      bottom: 'bottom',
      'bottom-left': 'bottom left',
      left: 'left',
      'top-left': 'top left',
    },
    scale: {
      '0': '0',
      '50': '.5',
      '75': '.75',
      '90': '.9',
      '95': '.95',
      '100': '1',
      '105': '1.05',
      '110': '1.1',
      '125': '1.25',
      '150': '1.5',
    },
    rotate: {
      '-180': '-180deg',
      '-90': '-90deg',
      '-45': '-45deg',
      '0': '0',
      '45': '45deg',
      '90': '90deg',
      '180': '180deg',
    },
    translate: (theme, { negative }) => ({
      ...theme('spacing'),
      ...negative(theme('spacing')),
      '-full': '-100%',
      '-1/2': '-50%',
      '1/2': '50%',
      full: '100%',
    }),
    skew: {
      '-12': '-12deg',
      '-6': '-6deg',
      '-3': '-3deg',
      '0': '0',
      '3': '3deg',
      '6': '6deg',
      '12': '12deg',
    },
    transitionProperty: {
      none: 'none',
      all: 'all',
      default: 'background-color, border-color, color, fill, stroke, opacity, box-shadow, transform',
      colors: 'background-color, border-color, color, fill, stroke',
      opacity: 'opacity',
      shadow: 'box-shadow',
      transform: 'transform',
    },
    transitionTimingFunction: {
      linear: 'linear',
      in: 'cubic-bezier(0.4, 0, 1, 1)',
      out: 'cubic-bezier(0, 0, 0.2, 1)',
      'in-out': 'cubic-bezier(0.4, 0, 0.2, 1)',
    },
    transitionDuration: {
      '75': '75ms',
      '100': '100ms',
      '150': '150ms',
      '200': '200ms',
      '300': '300ms',
      '500': '500ms',
      '700': '700ms',
      '1000': '1000ms',
    },
    customForms: theme => ({
      default: {
        'input, textarea, multiselect, select, checkbox': {
          borderRadius: 0,
        },
        'input, textarea, multiselect, select': {
          color: theme('colors.gray.600'),
          borderColor: theme('colors.gray.600'),
          display: 'block',
          lineHeight: theme('lineHeight.tight'),
          width: '100%',
          '&::placeholder': {
            color: theme('colors.gray.400'),
          },
          '&:disabled': {
            backgroundColor: theme('colors.gray.200'),
            opacity: theme('opacity.75'),
            cursor: theme('cursor.not-allowed'),
          },
        },
        'checkbox, radio': {
          color: theme('colors.gray.500'),
          borderColor: theme('colors.gray.600'),
          '&:disabled': {
            backgroundColor: theme('colors.gray.200'),
            opacity: theme('opacity.75'),
            cursor: theme('cursor.not-allowed'),
          },
        },
      },
    }),
  },
  variants: {
    accessibility: ['responsive', 'focus'],
    alignContent: ['responsive'],
    alignItems: ['responsive'],
    alignSelf: ['responsive'],
    appearance: [],
    backgroundAttachment: ['responsive'],
    backgroundColor: ['responsive', 'hover', 'focus', 'disabled'],
    backgroundPosition: ['responsive'],
    backgroundRepeat: [],
    backgroundSize: ['responsive'],
    borderCollapse: ['responsive'],
    borderColor: ['responsive', 'hover', 'focus'],
    borderRadius: ['responsive'],
    borderStyle: ['responsive'],
    borderWidth: ['responsive'],
    boxShadow: ['responsive', 'hover', 'focus'],
    boxSizing: [],
    clear: ['responsive'],
    cursor: ['disabled'],
    display: ['responsive'],
    fill: [],
    flex: ['responsive'],
    flexDirection: ['responsive'],
    flexGrow: ['responsive'],
    flexShrink: ['responsive'],
    flexWrap: ['responsive'],
    float: ['responsive'],
    fontFamily: [],
    fontSize: ['responsive'],
    fontSmoothing: [],
    fontStyle: [],
    fontWeight: ['responsive', 'hover', 'focus'],
    gap: ['responsive'],
    gridAutoFlow: ['responsive'],
    gridColumn: ['responsive'],
    gridColumnEnd: ['responsive'],
    gridColumnStart: ['responsive'],
    gridRow: ['responsive'],
    gridRowEnd: ['responsive'],
    gridRowStart: ['responsive'],
    gridTemplateColumns: ['responsive'],
    gridTemplateRows: ['responsive'],
    height: ['responsive'],
    inset: ['responsive'],
    justifyContent: ['responsive'],
    letterSpacing: [],
    lineHeight: ['responsive'],
    listStylePosition: [],
    listStyleType: [],
    margin: ['responsive'],
    maxHeight: ['responsive'],
    maxWidth: ['responsive'],
    minHeight: ['responsive'],
    minWidth: ['responsive'],
    objectFit: ['responsive'],
    objectPosition: ['responsive'],
    opacity: ['responsive', 'hover', 'focus', 'disabled'],
    order: ['responsive'],
    outline: ['responsive', 'focus'],
    overflow: ['responsive'],
    padding: ['responsive'],
    placeholderColor: ['focus'],
    pointerEvents: [],
    position: ['responsive'],
    resize: [],
    rotate: ['responsive', 'hover', 'focus'],
    scale: ['hover', 'focus'],
    skew: ['responsive', 'hover', 'focus'],
    stroke: [],
    strokeWidth: [],
    tableLayout: ['responsive'],
    textAlign: ['responsive'],
    textColor: ['responsive', 'hover', 'focus'],
    textDecoration: ['hover', 'focus'],
    textTransform: [],
    transform: ['responsive'],
    transformOrigin: ['responsive'],
    transitionDuration: ['responsive'],
    transitionProperty: ['responsive'],
    transitionTimingFunction: ['responsive'],
    translate: ['responsive', 'hover', 'focus'],
    userSelect: [],
    verticalAlign: [],
    visibility: [],
    whitespace: [],
    width: ['responsive'],
    wordBreak: [],
    zIndex: ['responsive'],
  },
}
